### PR TITLE
Update buddy guidance to be consistent

### PR DESCRIPTION
**Pull request by jbevan4**
The buddy guidance file was named in a different convention to other files. I've made this snake case like our other files.

### CODE REVIEW

**Review by adrianclay — APPROVED** [review]
:shipit:

**Review by duncanmadetech — APPROVED** [review]
How do files with spaces in like that even work? Surely the end just floats away into the internet?

**Comment by jbevan4** [comment]
Anyone know why this last check isn't passing?

**Comment by duncanmadetech** [comment]
The CircleCI job doesn't seem to have triggered 🤷‍♂️

**Comment by duncanmadetech** [comment]
Make another fake commit?

**Comment by baarkerlounger** [comment]
Not triggered on my PR either. Circle is showing a "Server under maintenance" warning so might be that.

**Pull request merged**
