### PR TITLE
Remove all role expectations from engineer roles

### PR DESCRIPTION
**Pull request by lukemorton**
## Why

We are rolling out SFIA to all engineers this quarter and so expectations are no longer required.

## What

Remove all expectations from engineer roles.

### CODE REVIEW

**Comment by cob16** [comment]
Will SFIA be added to the handbook in its place?

**Comment by lukemorton** [comment]
Interesting question @cob16, they probably should be. I think having explicit expectations in the Handbook to indicate what we expect are really important. The new SFIA expectations are wrapped up in Spreadsheets at the moment which needs untangling. 

The current expectations in this Handbook are out of date and I think I'd prefer to remove them rather than have incorrect information in here.

**Comment by kjdchapman** [comment]
Is a placeholder about SFIA is better than leaving a blank?

> We use [SFIA](https://www.sfia-online.org/en) to explain the expectations of a role. 
We're hoping to add more detail about this soon.

(The SFIA official docs aren't particularly friendly, so not sure)

**Comment by adrianclay** [comment]
I remember reading these and thinking they were really useful context when applying/deciding whether I should apply to MT.

**Comment by StevenLeighton21** [comment]
SFIA doesn't entirely replace these, does it? We're still working to uphold these expectations afaik.

**Comment by lukemorton** [comment]
SFIA largely does replace these expectations and we've promoted people even though these expectations have not been met at all, so they are fairly inaccurate.

We will aim to add examples based on SFIA later this year.

**Pull request merged**
