### PR TITLE
Update and rename friday_drinks.md to Getting together.md

### PR DESCRIPTION
**Pull request by Camsmitti**
Updating the Friday Drinks page to be more inclusive and include all types of team and company wide socials.

### CODE REVIEW

**Comment by owenblacker** [comment]
@Camsmitti The failing test above is because several other pages (all the roles pages, in pticlr) link to the old page name. Can you update those links in this same branch `Camsmitti-patch-2`, please? If you need to do that through the web interface, you should be able to [access the branch `Camsmitti-patch-2` here](https://github.com/madetech/handbook/tree/Camsmitti-patch-2).

**Comment by Camsmitti** [comment]
Can you please explain this to me in a way it might make more sense 😅
thank you!!



*Cam Smitti **(She / Her)*

Assoc. People Ops & Culture Advisor


<https://www.madetech.com/?utm_source=signaturesatori&utm_medium=email&utm_campaign=general_signature>

www.madetech.com
<https://www.madetech.com/?utm_source=signaturesatori&utm_medium=email&utm_campaign=general_signature>


twitter.com/madetech

linkedin.com/company/madetech <https://www.linkedin.com/company/madetech/>

**Comment by cob16** [comment]
@Camsmitti given you have renamed the file, the links to the old file in the handbook need to updated to the new one

Here is a list of all the places that contain the old link:
1. roles/associate_delivery_manager.md
2. roles/head_of_capability_practice.md
3. roles/head_of_delivery_management.md
4. roles/lead_business_analyst.md
5. roles/lead_data_engineer.md
6. roles/lead_delivery_manager.md
7. roles/lead_product_manager.md
8. roles/lead_security_engineer.md
9. roles/lead_software_engineer.md
10. roles/associate_software_engineer.md
11. roles/mid_business_analyst.md
12. roles/mid_data_engineer.md
13. roles/mid_product_manager.md
14. roles/mid_software_engineer.md
15. roles/principal_business_analyst.md
16. roles/principal_delivery_manager.md
17. roles/principal_security_engineer.md
18. roles/principal_technologist.md
19. roles/senior_business_analyst.md
20. roles/senior_data_engineer.md
21. roles/senior_data_scientist.md
22. roles/senior_delivery_manager.md
23. roles/senior_product_manager.md
24. roles/senior_software_engineer.md
25. roles/_delivery_manager.md
26. README.md

**Comment by cob16** [comment]
The last bit of this PR is to replace :beers: with something more inclusive

**Review by cob16 — APPROVED** [review]

**Pull request merged**
