### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by EThom73**
What?
Made Tech Development Practices and Policies README

Why?
ISO 27001 compliance

NOTE - this section of the IMS guide doesn't have a team owning it (e.g. Operations Team/People Team). I have left all references to the team as TBD. This branch cannot merge until that is decided

### CODE REVIEW

**Comment by EThom73** [comment]
Sure - this is just a migration (and simplification) of what already existed in our ISO 27001 documentation.

**Comment by EThom73** [comment]
Have updated to Technology team, but don't know what David's official title is now. What should I enter?

**Comment by yusufsheiqh** [comment]
> Have updated to Technology team, but don't know what David's official title is now. What should I enter?

I believe it is Senior Technical Advisor.

**Comment by EThom73** [comment]
Awesome - Thanks Yusuf. Have updated

**Comment by lukemorton** [comment]
We can take this on next week if that works?

**Pull request closed without merging**
