### PR TITLE
Add information on "Raising an Issue"

### PR DESCRIPTION
**Pull request by lukemorton**
Related to addressing #80 and following on from the discussion during comradrospective this week, I've put together a first draft of information to empower the Made Tech team to be able to resolve issues both informally and formally.

All staff should take the following steps, if possible, to resolve their issue:

- Have a conversation with the person involved
- Raise feedback via Continuous Feedback
- Ask a colleague to intervene on your behalf
- Seek Third Party Advice
- Mediation
- Formal Grievance Procedure
- Arbitration Tribunals and Civil Courts

Not the loveliest subject but I really think it's important we outline procedure so everyone feels empowered and protected.

### CODE REVIEW

**Comment by craigjbass** [comment]
I think there are two parts to this, escalation for things that are non-severe and highly severe things. We need to support people in both categories.

I feel the steps listed escalate quickly. I think there needs to be more internal steps first.

For example, while nobody is a trained mediator, I’d expect the second step to be to encourage someone to facilitate a meeting between yourself and a person you are at conflict with.

**Comment by lukemorton** [comment]
I can see that. I think it's really important for most issues to be solved in the first few steps. It does escalate but I'd expect 90% of problems to be solved by the first step, 9% solved by the second, .9% solved by the next, etc.

I feel like "Ask a colleague to intervene on your behalf" is the step you talk about. Do you think we could add another paragraph to that section (or others) related to encouraging facilitation?

**Comment by craigjbass** [comment]
I think there is a difference between intervening and facilitating.

**Comment by lukemorton** [comment]
You think the facilitation could be added to "Have a conversation with the person involved" as an alternative then?

**Pull request merged**
