### PR TITLE
Add guidance on putting plates and crockery in to the dishwasher

### PR DESCRIPTION
**Pull request by chrisblackburn**

### CODE REVIEW

**Comment by kjdchapman** [comment]
image

You found an excellent guide.

**Comment by heidar** [comment]
Well this is awkward, I didn't see this and I wrote my own PR on dishwasher use.. https://github.com/madetech/handbook/pull/230

**Comment by heidar** [comment]
I've added the link about dishwasher loading to mine as well. I suggest we close this in favour of #230.

**Comment by chrisblackburn** [comment]
Closing this in favour of Heidar's VASTLY IMPROVED offering

**Pull request closed without merging**
