### PR TITLE
Create Confidentiality_Agreements

### PR DESCRIPTION
**Pull request by EThom73**
**What:**
A short PR stating how Made Tech uses confidentiality agreements. 

**Why:**
It's very important to be clear and transparent around our use of confidentiality agreements. It not only ensures our team are handling information appropriately, but also instills confidence in our clients that Made tech is a safe and reliable partner to do business with. 

The use of NDAs for visitors also allows us to protect any sensitive work from falling into the wrong hands.

### CODE REVIEW

**Comment by chrisblackburn** [comment]
Trying to figure out who the audience is for this one. Feels like maybe there's one thing to emerge:

- Non-disclosure agreements (people sometimes ask about how to do these - so guidance on that)

Could we lose the rest?

**Comment by chrisblackburn** [comment]
And also add something helpful pointing to the NDA template etc.

**Comment by EThom73** [comment]
OK. 

We don't seem to have a NDA template, but lots of versions. Is this the correct one? https://docs.google.com/document/d/1AcbQUpfiqgW_6ze0ewGrmUsIODnYRnzw1ZHxkw08w5Y/edit

**Comment by chrisblackburn** [comment]
Yep, I think that's derived from the latest doc.

I think this is the template: https://docs.google.com/document/d/1YESByvaOv06azyq6JTNqmD9vsHh224lQ9urKV0p4_pY/edit

**Comment by EThom73** [comment]
have updated the link and also tweaked the contents to cover situations where team members may need to refer to these guidelines

**Pull request merged**
