### PR TITLE
Update raising_an_issue.md

### PR DESCRIPTION
**Pull request by EThom73**
Includes
1. Reference to head of People rather than Directors in process.
2. Outlines how Made Tech approaches disciplinary procedure. This is important for the purposes of transparency with our employees.

### CODE REVIEW

**Comment by chrisblackburn** [comment]
As with the Capability Procedure (https://github.com/madetech/handbook/blob/master/guides/process/people/capability_procedure.md) perhaps instead of talking about "a process" we could mention that we follow ACAS CoP for dealing with disciplinary proceedings?

Otherwise LGTM, should probably have @yaseminercan give this a once over to merge too

**Comment by EThom73** [comment]
Think that might be for a new PR? Don't know that it applies to the amendments I've made here.

**Comment by chrisblackburn** [comment]
This PR adds "we have a disciplinary procedure in place" without providing information on that. I wonder if this is more genuine:

While we always prefer to handle minor misdemeanours in an informal way, we follow the ACAS CoP for handling disciplinary procedures, which will be invoked in the unusual event that a member of staff breaches any of our Company policies or performs (or assists in) an illegal or immoral activity.

**Comment by yaseminercan** [comment]
Great to link to Acas. maybe we can add the link to acas too: https://www.acas.org.uk/article/2174/Discipline-and-grievance-Acas-Code-of-Practice

**Comment by EThom73** [comment]
Cool. Have linked that directly.

**Comment by chrisblackburn** [comment]
LGTM as long as @yaseminercan is happy

**Comment by yaseminercan** [comment]
Happy :) all good from me

**Pull request merged**
