### PR TITLE
Introduce Senior Engineer role expectations

### PR DESCRIPTION
**Pull request by lukemorton**
Introducing a Senior Engineer role, sharing some expectations with Lead and defining it's own too.

I'd be interested to know if anyone thinks we're missing any here.

### CODE REVIEW

**Comment by chrisblackburn** [comment]
Maybe something about picking up new languages/frameworks/tools easily?
Championing / leading the rollout by example of new technologies (thinking Richard with Elixir on Evermore, for example)?
Expert lean/agile? Or is this just code?

**Comment by craigjbass** [comment]
@chrisblackburn Lean/Agile encourages behaviour where tech is used to further the team's efficiency. If we leave it out then I think these expectations massively fall down - "Tech for the sake of it"

**Comment by chrisblackburn** [comment]
@craigjbass agree. It's not in there as an expectation for this role at present (AFAICS)

**Comment by lukemorton** [comment]
@craigjbass and @chrisblackburn I believe I've addressed your suggestions.

**Pull request merged**
